### ISSUE TITLE
Unicode não funcionou

### ISSUE THREAD

**Issue by mill3na** [leticiadutra22-23/organize-it-for-me#2]
https://github.com/leticiadutra22-23/organize-it-for-me/blob/de5e3fc9615183ab46549565b799fd812a125c51/main.swift#L30

Oi, Letícia. Adorei a sua ideia!

Gostaria só de te sugerir que use o próprio emoji ao invés do unicode. Ele não funcionou por aqui :( 
Para visualizar, você pode apertar a tecla [fn], uma lista aparecerá e você pode escolher.

<img width="585" alt="Captura de Tela 2022-03-31 às 10 03 00" src="https://user-images.githubusercontent.com/58698807/161061967-64b08b45-83d2-4705-9d10-a306491875b7.png">

Para deixar  código mais limpo, você pode separá-lo em pequenas funções. Qualquer dúvida, pode me chamar! :)

**Comment by leticiadutra22-23** [comment]
Oi oi, amg!!! Eram para ser cores kkkkk infelizmente não funciona bem no Xcode ao rodar, mas no replit exibe melhor e de maneira mais estética 😅 Coloquei o link no ReadMe!
